### ISSUE TITLE
Black screen and no output.

### ISSUE THREAD

**Issue by Vpathy** [psiorx/Unity-Fisheye#1]
I tried to import your pack. I get a blank screen and issue with no camera component attached. Resolved it by pointing it to main camera. but still i see black screen in unity3d 2018. But the youtubevideo is really cool.

**Comment by ZijianHan** [comment]
Hi, how did you solve the issue? I have the same issue as you mentioned above

**Comment by benwest** [comment]
I've got this working in Unity 2021.2.5f1 like this:
- Add a Camera component to the CubemapCamera object and disable it.
- Delete the OnRenderImage function from the RenderCubemap script.
